// DevToNetProfiler.idl: IDL-Quelle für DevToNetProfiler
//

// Diese Datei wird mit dem MIDL-Tool bearbeitet,
// generieren die Typbibliothek (DevToNetProfiler.tlb) und den Marshallingcode.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(103d660d-1cb4-4410-85dd-67b3aa489626),
	helpstring("INetProfiler Interface"),
	pointer_default(unique)
]
interface IProfiler : IUnknown {
};
[
	uuid(DA37BE57-9EA8-4622-BDF5-E724CD3A60C1),
	version(1.0),
	helpstring("DotNetProfiler 1.0 Type Library")
]
library DotNetProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(9E2B38F2-7355-4C61-A54F-434B7AC266C0),
		helpstring("Profiler Class")
	]
	coclass Profiler
	{
		[default] interface IUnknown;
	};
};